attacked_classes:
- 0
batch_size: 128
data_paths:
- /data/bone
dataset_name: bone_attacked
device: cuda
eval_every_n_epochs: 5
img_size: 224
loss: cross_entropy
lr: 0.001
model_name: efficientnet_b0
model_savedir: /data/output
num_epochs: 100
optimizer: adam
p_artifact: 0.5
pretrained: true
store_every_n_epochs: 150
wandb_api_key: your_api_key
wandb_project_name: your_project_name
