artifacts_file: data/artifacts_bone.json
batch_size: 128
data_paths:
- /data/bone
dataset_name: bone
device: cuda
eval_every_n_epochs: 5
img_size: 224
loss: cross_entropy
lr: 0.005
model_name: vgg16
model_savedir: checkpoints
num_epochs: 100
optimizer: sgd
pretrained: true
store_every_n_epochs: 150
wandb_api_key: your_api_key
wandb_project_name: your_project_name
