artifact: skin_marker-band_aid-ruler
batch_size: 64
ckpt_path: checkpoints/vgg16_RRR_ExpMax_sgd_lr0.0001_lamb500_skin_marker-band_aid.ckpt
ckpt_path_corrected: checkpoints/vgg16_RRR_ExpMax_sgd_lr0.0001_lamb500_skin_marker-band_aid-ruler/last.ckpt
data_path: /data/dataset_isic2019
dataset_name: isic
device: cuda
eval_every_n_epochs: 5
lamb: 500
layer_name: features.28
loss: cross_entropy
lr: 0.0001
method: RRR_ExpMax
model_name: vgg16
num_epochs: 10
optimizer: sgd
store_every_n_epochs: 50
wandb_api_key: your_api_key
wandb_project_name: your_project_name
