artifacts_file: data/artifacts_isic.json
batch_size: 128
data_paths:
- /data/dataset_isic2019
dataset_name: isic
device: cuda
eval_every_n_epochs: 5
img_size: 224
loss: cross_entropy
lr: 0.001
model_name: efficientnet_b0
model_savedir: /data/output
num_epochs: 150
optimizer: adam
pretrained: true
store_every_n_epochs: 100
wandb_api_key: your_api_key
wandb_project_name: your_project_name
