artifact: artificial
attacked_classes:
- 0
batch_size: 64
ckpt_path: checkpoints/checkpoint_resnet18_bone_attacked.pth
ckpt_path_corrected: checkpoints/resnet18_RRR_ExpMax_sgd_lr0.0001_lamb50_artificial_last_conv/last.ckpt
data_paths:
- /data/bone
dataset_name: bone_attacked
device: cuda
img_size: 224
lamb: 50
layer_name: last_conv
loss: cross_entropy
lr: 0.0001
method: RRR_ExpMax
model_name: resnet18
num_epochs: 10
optimizer: sgd
p_artifact: 0.5
wandb_api_key: your_api_key
wandb_project_name: your_project_name
