artifact: big_l
artifacts_file: data/artifacts_bone.json
batch_size: 64
ckpt_path: checkpoints/checkpoint_efficientnet_b0_bone_last.pth
ckpt_path_corrected: checkpoints/efficientnet_b0_PClarc_sgd_lr0.0001_lamb1_big_l_last_conv/last.ckpt
data_paths:
- /data/bone
dataset_name: bone
device: cuda
img_size: 224
lamb: 1
layer_name: last_conv
loss: cross_entropy
lr: 0.0001
method: PClarc
model_name: efficientnet_b0
num_epochs: 10
optimizer: sgd
wandb_api_key: your_api_key
wandb_project_name: your_project_name
