artifact: big_l
artifacts_file: data/artifacts_bone.json
batch_size: 64
ckpt_path: checkpoints/checkpoint_vgg16_bone_last.pth
ckpt_path_corrected: checkpoints/vgg16_RRR_ExpMax_sgd_lr0.0001_lamb50_big_l_features.28/last.ckpt
data_paths:
- /data/bone
dataset_name: bone
device: cuda
img_size: 224
lamb: 50
layer_name: features.28
loss: cross_entropy
lr: 0.0001
method: RRR_ExpMax
model_name: vgg16
num_epochs: 10
optimizer: sgd
wandb_api_key: your_api_key
wandb_project_name: your_project_name
